[build]
  builder = "NIXPACKS"
  buildCommand = "npm install"

[deploy]
  startCommand = "npm start"
  healthcheckPath = "/health"
  healthcheckTimeout = 300
  restartPolicyType = "ON_FAILURE"
  restartPolicyMaxRetries = 3

[environments.production]
  [environments.production.variables]
    NODE_ENV = "production"
    PORT = "8080"

[environments.staging]
  [environments.staging.variables]
    NODE_ENV = "staging"
    PORT = "8080"

[environments.development]
  [environments.development.variables]
    NODE_ENV = "development"
    PORT = "8080"
